### ISSUE TITLE
Add branch protection

### ISSUE THREAD

**Issue by gvegayon** [EpiForeSITE/epiworld-forecasts#10]

**Comment by apulsipher** [comment]
@gvegayon I added basic protections to main: restricting deletions and force pushing. Are there any additional branch protections you want to add?
For example, we could add "Require a pull request before merging"

**Comment by gvegayon** [comment]
Let's go with that one, "Requiring PRs".

**Comment by apulsipher** [comment]
Okay, done. Closing the issue.
